apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: redis-test-ms-gcp-secrets
  namespace: dev
spec:
  provider: gcp
  parameters:
    secrets: |

      - resourceName: "projects/inhouz-dev/secrets/mongourl/versions/latest"
        fileName: "mongourl"
      - resourceName: "projects/inhouz-dev/secrets/sessionsecret/versions/latest"
        fileName: "sessionsecret"
      - resourceName: "projects/inhouz-dev/secrets/clientsecretkey/versions/latest"
        fileName: "clientsecretkey"
      - resourceName: "projects/inhouz-dev/secrets/clientpublickey/versions/latest"
        fileName: "clientpublickey"
      - resourceName: "projects/inhouz-dev/secrets/sendgridapikey/versions/latest"
        fileName: "sendgridapikey"
      - resourceName: "projects/inhouz-dev/secrets/openexchangeratesapikey/versions/latest"
        fileName: "openexchangeratesapikey"
      - resourceName: "projects/inhouz-dev/secrets/lemlistapikey/versions/latest"
        fileName: "lemlistapikey"
      - resourceName: "projects/inhouz-dev/secrets/s3accesskeyid/versions/latest"
        fileName: "s3accesskeyid"
      - resourceName: "projects/inhouz-dev/secrets/s3bucketname/versions/latest"
        fileName: "s3bucketname"
      - resourceName: "projects/inhouz-dev/secrets/s3secretkey/versions/latest"
        fileName: "s3secretkey"
      - resourceName: "projects/inhouz-dev/secrets/stripeapikey/versions/latest"
        fileName: "stripeapikey"
      - resourceName: "projects/inhouz-dev/secrets/cloudflareauthkey/versions/latest"
        fileName: "cloudflareauthkey"
      - resourceName: "projects/inhouz-dev/secrets/cloudflarezoneid/versions/latest"
        fileName: "cloudflarezoneid"
      - resourceName: "projects/inhouz-dev/secrets/gcsclientemail/versions/latest"
        fileName: "gcsclientemail"
      - resourceName: "projects/inhouz-dev/secrets/gcsclientid/versions/latest"
        fileName: "gcsclientid"
      - resourceName: "projects/inhouz-dev/secrets/gcsclientx509certurl/versions/latest"
        fileName: "gcsclientx509certurl"
      - resourceName: "projects/inhouz-dev/secrets/gcsprivatekey/versions/latest"
        fileName: "gcsprivatekey"
      - resourceName: "projects/inhouz-dev/secrets/gcsprivatekeyid/versions/latest"
        fileName: "gcsprivatekeyid"
      - resourceName: "projects/inhouz-dev/secrets/gcsprojectid/versions/latest"
        fileName: "gcsprojectid"
      - resourceName: "projects/inhouz-dev/secrets/redishost/versions/latest"
        fileName: "redishost"
      - resourceName: "projects/inhouz-dev/secrets/redispassword/versions/latest"
        fileName: "redispassword"
