const isLoggedIn = require('../../middlewares/login/checkLogin');
const subdomainCheck = require('../../middlewares/subdomain/singleSubdomainValidation');
const isAllowedDeveloper = require('../../middlewares/permissions/isAllowedDeveloper');
const createApp = require('../../services/appBuilder/createApp');
const getApp = require('../../services/appBuilder/getApp');
const getCompressedApp = require('../../services/appBuilder/getCompressedApp');
const editApp = require('../../services/appBuilder/editApp');
const getApps = require('../../services/appBuilder/getApps');
const editAppPage = require('../../services/appBuilder/editAppPage');
const getUniqueId = require('../../services/appBuilder/getUniqueId');
const createFolder = require('../../services/appBuilder/appFolder/createFolder');
const editFolder = require('../../services/appBuilder/appFolder/editFolder');
const deleteAppFolder = require('../../services/appBuilder/appFolder/deleteAppFolder');
const getFolder = require('../../services/appBuilder/appFolder/getFolder');
const getFolders = require('../../services/appBuilder/appFolder/getFolders');
const folderNameAvailability = require('../../services/appBuilder/appFolder/folderNameAvailability');
const appFieldAvailability = require('../../services/appBuilder/appFieldAvailability');
const saveStyle = require('../../services/appBuilder/savedStyles/saveStyle');
const editAppStyles = require('../../services/appBuilder/savedStyles/editAppStyles');
const deletAppStyles = require('../../services/appBuilder/savedStyles/deletAppStyles');
const getAppStyles = require('../../services/appBuilder/savedStyles/getAppStyles');
const createStyleGuide = require('../../services/appBuilder/styleGuide/createStyleGuide');
const editStyleGuide = require('../../services/appBuilder/styleGuide/editStyleGuide');
const deleteStyleGuide = require('../../services/appBuilder/styleGuide/deleteStyleGuide');
const getStyleGuide = require('../../services/appBuilder/styleGuide/getStyleGuide');
const savedStyleNameCheck = require('../../services/appBuilder/savedStyles/savedStyleNameCheck');
const logExternalUserEditorAccess = require('../../services/appBuilder/logExternalUserEditorAccess');
const setAppPassword = require('../../services/appBuilder/appAccess/setAppPassword');
const changeAppPassword = require('../../services/appBuilder/appAccess/changeAppPassword');
const requestAppPasswordChange = require('../../services/appBuilder/appAccess/requestAppPasswordChange');
const saveAppElement = require('../../services/appBuilder/elements/saveAppElement');
const deleteSavedAppElement = require('../../services/appBuilder/elements/deleteSavedAppElement');
const getSavedAppElements = require('../../services/appBuilder/elements/getSavedAppElements');
const deleteInhouzApp = require('../../services/appBuilder/deleteInhouzApp');
const companyAccountCheck = require('../../middlewares/company/companyAccountCheck');
const activateCustomDomain = require('../../services/appBuilder/customDomains/activateCustomDomain');
const deactivateCustomDomain = require('../../services/appBuilder/customDomains/deactivateCustomDomain');
const cloneApp = require('../../services/appBuilder/cloneApp');
const getAppsByName = require('../../services/appBuilder/getAppsByName');
const checkServerLogin = require('../../middlewares/login/checkServerLogin');
const serverEncryptedLogin = require('../../middlewares/login/serverEncryptedLogin');
const clientEncryptedLogin = require('../../middlewares/login/clientEncryptedLogin');
const apiKeyValidation = require('../../middlewares/apiKey/apiKeyValidation');
const undeployApp = require('../../services/appBuilder/undeployApp');
const commitApp = require('../../services/appBuilder/commitApp');
const appRebaseFallback = require('../../services/appBuilder/appRebaseFallback');
const setCommitVersion = require('../../services/appBuilder/setCommitVersion');
const getAppCommits = require('../../services/appBuilder/getAppCommits');
const getAppRebaseFallbacks = require('../../services/appBuilder/getAppRebaseFallbacks');
const encGetCompressedApp = require('../../services/appBuilder/encGetCompressedApp');
const hasDeletePermission = require('../../middlewares/permissions/hasDeletePermission');

module.exports = (app) => {
    app.post('/api/appbuilder/createapp', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, createApp);
    app.post('/api/appbuilder/cloneapp', apiKeyValidation, clientEncryptedLogin, serverEncryptedLogin, checkServerLogin, isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, cloneApp);
    app.post('/api/appbuilder/getapp', apiKeyValidation, clientEncryptedLogin, serverEncryptedLogin, checkServerLogin, isLoggedIn, subdomainCheck, isAllowedDeveloper, getApp);
    app.post('/api/appbuilder/getcompressedapp', isLoggedIn, subdomainCheck, isAllowedDeveloper, getCompressedApp);
    app.post('/api/appbuilder/encgetcompressedapp', encGetCompressedApp);
    app.post('/api/appbuilder/editapp', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, editApp);
    app.post('/api/appbuilder/commitapp', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, commitApp);
    app.post('/api/appbuilder/getappcommits', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, getAppCommits);
    app.post('/api/appbuilder/setcommitversion', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, setCommitVersion);
    app.post('/api/appbuilder/setrebasefallback', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, appRebaseFallback);
    app.post('/api/appbuilder/getrebasefallbacks', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, getAppRebaseFallbacks);
    app.post('/api/appbuilder/undeploy', isLoggedIn, subdomainCheck, isAllowedDeveloper, undeployApp);
    app.post('/api/appbuilder/getapps', isLoggedIn, subdomainCheck, isAllowedDeveloper, getApps);
    app.post('/api/appbuilder/getappsbyname', isLoggedIn, subdomainCheck, isAllowedDeveloper, getAppsByName);
    app.post('/api/appbuilder/activatecustomdomain', isLoggedIn, subdomainCheck, isAllowedDeveloper, activateCustomDomain);
    app.post('/api/appbuilder/deactivatecustomdomain', isLoggedIn, subdomainCheck, isAllowedDeveloper, deactivateCustomDomain);
    app.post('/api/appbuilder/deleteapp', isLoggedIn, subdomainCheck, isAllowedDeveloper, hasDeletePermission, deleteInhouzApp);
    app.post('/api/appbuilder/serverdeleteapp', apiKeyValidation, clientEncryptedLogin, serverEncryptedLogin, checkServerLogin, isLoggedIn, deleteInhouzApp);
    app.post('/api/appbuilder/logexternalusereditoraccess', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, logExternalUserEditorAccess);
    // app.post('/api/appbuilder/editpage', isLoggedIn, subdomainCheck, isAllowedDeveloper, editAppPage);
    app.post('/api/appbuilder/getuniqueid', isLoggedIn, subdomainCheck, isAllowedDeveloper, getUniqueId);
    app.post('/api/appbuilder/fieldnamecheck', isLoggedIn, subdomainCheck, isAllowedDeveloper, appFieldAvailability);
    app.post('/api/appbuilder/appfolder/create', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, createFolder);
    app.post('/api/appbuilder/appfolder/edit', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, editFolder);
    app.delete('/api/appbuilder/appfolder/delete/:folderId', isLoggedIn, subdomainCheck, isAllowedDeveloper, deleteAppFolder);
    app.get('/api/appbuilder/appfolder/getfolder/:folderId', isLoggedIn, subdomainCheck, isAllowedDeveloper, getFolder);
    app.post('/api/appbuilder/appfolder/getfolders', isLoggedIn, subdomainCheck, isAllowedDeveloper, getFolders);
    app.post('/api/appbuilder/appfolder/foldernamecheck', isLoggedIn, subdomainCheck, isAllowedDeveloper, folderNameAvailability);
    app.post('/api/appbuilder/savedstyles/create', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, saveStyle);
    app.post('/api/appbuilder/savedstyles/edit', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, editAppStyles);
    app.delete('/api/appbuilder/savedstyles/delete/:appId/:styleId', isLoggedIn, subdomainCheck, isAllowedDeveloper, deletAppStyles);
    app.post('/api/appbuilder/savedstyles/getstyles', isLoggedIn, subdomainCheck, isAllowedDeveloper, getAppStyles);
    app.post('/api/appbuilder/savedstyles/namecheck', isLoggedIn, subdomainCheck, isAllowedDeveloper, savedStyleNameCheck);
    app.post('/api/appbuilder/styleguide/create', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, createStyleGuide);
    app.post('/api/appbuilder/styleguide/edit', isLoggedIn, subdomainCheck, companyAccountCheck, isAllowedDeveloper, editStyleGuide);
    app.delete('/api/appbuilder/styleguide/delete/:appId/:styleGuideId', isLoggedIn, subdomainCheck, isAllowedDeveloper, deleteStyleGuide);
    app.post('/api/appbuilder/styleguide/getstyleguide', isLoggedIn, subdomainCheck, isAllowedDeveloper, getStyleGuide);
    app.post('/api/appbuilder/appaccess/setpassword', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, setAppPassword);
    app.post('/api/appbuilder/appaccess/changepassword', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, changeAppPassword);
    app.post('/api/appbuilder/appaccess/requestpasswordchange', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, requestAppPasswordChange);
    app.post('/api/appbuilder/elements/save', isLoggedIn, companyAccountCheck, subdomainCheck, isAllowedDeveloper, saveAppElement);
    app.post('/api/appbuilder/elements/delete', isLoggedIn, subdomainCheck, isAllowedDeveloper, deleteSavedAppElement);
    app.post('/api/appbuilder/elements/getsavedappelements', isLoggedIn, subdomainCheck, isAllowedDeveloper, getSavedAppElements);
}