apiVersion: v1
kind: Service
metadata:
  name: redis-test-ms-cluster-ip-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    component: redis-test-ms
  ports:
    - port: 5099
      targetPort: 5099
